### ISSUE TITLE
RxJS v6

### ISSUE THREAD

**Issue by rolaveric** [synapse-wireless-labs/jasmine-marbles#13]
RxJS v6 is currently in beta and comes with some breaking changes that effect jasmine-marbles.
Mostly some trivial module path updates.
eg. `Observable` now needs to be imported off `rxjs` instead of `rxjs/Observable`, and `TestScheduler` from `rxjs/testing` instead of `rxjs/testing/TestScheduler`.

RxJS v5 -> v6 upgrade guide: https://docs.google.com/document/d/12nlLt71VLKb-z3YaSGzUfx6mJbc34nsMXtByPUN35cg/preview

**Comment by brandonroberts** [comment]
Fixed via #14

**Comment by AnimaMundi** [comment]
It would be great to have this documented in the README, to let people know that if they are still on RxJS v5  that they should use v0.2 of jasmine-marbles.
