### ISSUE TITLE
latest jasmine/marbles module does NOT compile 

### ISSUE THREAD

**Issue by corvinrok** [synapse-wireless-labs/jasmine-marbles#20]
Trying to run Karma tests fails to build against latest jasmine/marbles/rxjs combos

IE. I do this:
`ng test`

against these `package.json` settings (included only pertinent items):
```
  "dependencies": {
    "rxjs": "5.5.8",
    "zone.js": "0.8.24"
  },
  "devDependencies": {
    "jasmine-core": "3.1.0",
    "jasmine-marbles": "0.3.1",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.4.2",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "1.0.0",
    "typescript": "2.8.1",
  }
```

This results in the following errors:

```
> ng test

 10% building modules 1/1 modules 0 active03 04 2018 15:21:45.014:WARN [karma]: No captured browser, open http://localhost:9876/
03 04 2018 15:21:45.020:INFO [karma]: Front-end scripts not present. Compiling...
[./src/polyfills.ts] ./src/polyfills.ts 0 bytes {polyfills} [built]
   [0] multi ./src/polyfills.ts 28 bytes {polyfills} [built]
[./src/test.ts] ./src/test.ts 0 bytes {main} [built]

ERROR in node_modules/jasmine-marbles/src/scheduler.d.ts(1,31): error TS2307: Cannot find module 'rxjs/testing'.
node_modules/jasmine-marbles/src/test-observables.d.ts(2,33): error TS2307: Cannot find module 'rxjs/internal/testing/SubscriptionLog'.
```

I am at a loss, since the same packages (on pre-3.x versions) with `ng build` are working fine (of course, the CLI uses webpack).  This does NOT happen when I use 
```
    "jasmine-core": "2.99.1",
    "jasmine-marbles": "0.2.0",
```

Losing my mind trying to understand what is up...

**Comment by brandonroberts** [comment]
The latest version `0.3.1` is for RxJS 6.x. You need to be on version `0.2.1` for RxJS 5.x

**Comment by ctaepper** [comment]
@brandonroberts so `0.3.1` actually contains a breaking change... this should require a major version bump, because it is breaking any projects depending on `^0.2.1`

**Comment by brandonroberts** [comment]
It is a breaking change and was reflected in the commit. `^0.3.0` is a major bump and would not be picked up by the `^0.2.0` constraint. If you are doing a fresh install you get the latest version

**Comment by ctaepper** [comment]
sorry, but a major version bump would be `1.0.0`. If I have `^0.2.1` defined in my package.json (default npm version range ), it would pick up `0.3.0` if it's available. Only defining `~0.2.1` would not pick up `0.3.0`

**Comment by brandonroberts** [comment]
https://semver.npmjs.com/ says otherwise if you search for `jasmine-marbles` and enter `^0.2.1` for the range

**Comment by ctaepper** [comment]
look at that, I learned [something new](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) today. if the major version is `0`, the minor version bump is considered a breaking change
