### ISSUE TITLE
Add Jest support

### ISSUE THREAD

**Issue by blove** [synapse-wireless-labs/jasmine-marbles#28]
## Feature Request

Add `jest` namespace to global TypeScript declaration in order to add `toBeObservable` and `toHaveSubscriptions` methods to the `Matchers` class.
This is to prevent the following TypeScript error in VS Code:

```
Property 'toBeObservable' does not exist on type 'Matchers<void>'.
```

## Describe any alternatives/workarounds you're currently using

No workaround is currently necessary as you can still execute Jest tests using jasmine-marbles.
You can ignore the error and execute the tests using the `toBeObersable()` method.

## Other information:

None.

## If accepted, I would be willing to submit a PR for this feature

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by patoncrispy** [comment]
This still seems to be an issue. I'm using jasmine-marbles `^0.3.1` and Jest `^23.6.0`. Message is a little different though: `Property 'toBeObservable' does not exist on type 'Matchers<Observable<Action>>'.`

**Comment by blove** [comment]
@patoncrispy I don't think a release has been cut yet with this PR.

**Comment by patoncrispy** [comment]
Ah OK! That makes sense. :) Will watch this space.

**Comment by brandonroberts** [comment]
`0.4.0` has been released

**Comment by mohyeid** [comment]
@brandonroberts any example how this will work with a list of actions?

**Comment by johnbendi** [comment]
@blove I already commented on the commit related to this. Please I am getting `All declarations of 'Matchers' must have identical type parameters` and `Generic type 'Matchers<R, T>' requires 2 type argument(s)` because of your choice of type parameter letter. Changing it from `jest.Matchers<T>` to `jest.Matchers<R>` solves the problem.

**Comment by felikf** [comment]
For future me:
JEST + jasmine marbles:

I switched to `jasmine-marbles: 0.5.0`. Then my test started to report some error about Jasmine not being found. So I switched to jest-marbles. But there was another issue reported here: https://stackoverflow.com/questions/55705040/marble-test-fails-with-jest-but-equivalent-test-succeeds-with-jasmine
