### ISSUE TITLE
Misguided use of `browser` field in package.json

### ISSUE THREAD

**Issue by lephyrus** [synapse-wireless-labs/jasmine-marbles#34]
I think the change in https://github.com/synapse-wireless-labs/jasmine-marbles/commit/f3f3f74fd3a8ef08d3d80c1610a68cabd83d0984 was misguided and it breaks my Rollup build.

*Why does it break my Rollup build?*

Because Rollup prioritizes the "browser" entry point over all others if present. But using named imports in the source code then leads to `'cold' is not exported by node_modules\jasmine-marbles\bundles\jasmine-marbles.umd.js`.

*Why should you not use the "browser" field for the UMD bundle?*

The "browser" field provides bundlers with an entry point to an alternative implementation that is optimized for a browser as opposed to expecting the Node stdlib to be available. From the [spec](https://github.com/defunctzombie/package-browser-field-spec):
>When a javascript module is prepared for use on a client there are two major concerns: certain features are already provided by the client, and certain features are not available. Features provided by a client can include http requests, websockets, dom manipulation. Features not available would include tcp sockets, system disk IO.
>
> The browser field is where the module author can hint to the bundler which elements (other modules or source files) need to be replaced when packaging.

The original entry points before the commit I mentioned were current best practice. Use the "module" field for modularized code and "main" for the UMD bundle. See for example https://github.com/angular/angular/blob/master/packages/core/package.json.

**Comment by brandonroberts** [comment]
Would you like to put in a PR for this fix?

**Comment by lephyrus** [comment]
Sure, done. 👍

**Comment by lephyrus** [comment]
@brandonroberts I could really use this fix, any chance of merging #35 and releasing?
