### ISSUE TITLE
Jasmine-Marbles ^0.5.0 does not work in Angular 8

### ISSUE THREAD

**Issue by Rlcolli4** [synapse-wireless-labs/jasmine-marbles#40]
I also comented on this https://github.com/synapse-wireless-labs/jasmine-marbles/issues/21 thread, but after upgrading to Angular 8 and Material 8 with the corresponding CLI and modules, Jasmine-Marble based tests will fail. We use these to test `ngrx effects`.

We get the following error when we try to run those tests:
<img width="1110" alt="Screen Shot 2019-06-04 at 11 16 11 AM" src="https://user-images.githubusercontent.com/12074293/58904320-225cee00-86bc-11e9-9806-3ae1495f0cd3.png">

**Comment by kekel87** [comment]
Hi, as workaround you can add 'jasmine-marbles' initialisation code in your test.ts file (source).

```typescript
// test.ts
import { addMatchers, getTestScheduler, initTestScheduler, resetTestScheduler } from 'jasmine-marbles';

jasmine.getEnv().beforeAll(() => {
  return addMatchers();
});
jasmine.getEnv().beforeEach(() => {
  initTestScheduler();
});
jasmine.getEnv().afterEach(() => {
  getTestScheduler().flush();
  resetTestScheduler();
});
```

**Comment by brandonroberts** [comment]
Fixed via https://github.com/synapse-wireless-labs/jasmine-marbles/pull/41
