### ISSUE TITLE
Something strange with npm versions

### ISSUE THREAD

**Issue by Karolis92** [synapse-wireless-labs/jasmine-marbles#43]
https://www.npmjs.com/package/jasmine-marbles has version 0.6.0, but I see only 0.5.0 in this repo.

I noticed this because my test stopped working when updated to 0.6.0. For some reason `toHaveSubscriptions` is broken. I will create other issue for that, as 0.5.0 has same.

Any idea what happened wit versions?

**Comment by brandonroberts** [comment]
v0.6.0 is tagged in this repo
