### ISSUE TITLE
Better test fail reporting

### ISSUE THREAD

**Issue by krzysztof-grzybek** [synapse-wireless-labs/jasmine-marbles#51]
Hi!
It's a feature request - better test fail reporting:

I would like to have a graphical representation of the received stream in comparison with the expected stream.

The most basic scenario:
Let's say we expect stream `--a`, but we received `-a`. Currently we report a message like:

```
Expected $[0].frame = 10 to equal 20.
```

I would like to have additionally a visual representation of these streams:
```
Expected: --a
Received: -a
Expected $[0].frame = 10 to equal 20.
```

**Comment by xileftenurb** [comment]
I have a pull request doing exacly that #50

**Comment by krzysztof-grzybek** [comment]
@xileftenurb Awesome! I will try it next week and then I will give you some feedback.

**Comment by krzysztof-grzybek** [comment]
@brandonroberts any update on that?
