### ISSUE TITLE
Using toPromise results in jasmine warning spec has no expectations

### ISSUE THREAD

**Issue by dtaylor84** [synapse-wireless-labs/jasmine-marbles#52]
(N.B. I'm fairly new to rxjs and jasmine-marbles, so may well be missing something obvious! However, I have searched without success for any clue as to what I'm doing wrong or why things should behave this way.)

**To Reproduce**
(presumably unrelated to use of angular, but haven't confirmed):

1.  ng new empty-project
2. cd empty-project
3. npm install jasmine-marbles
4. Create src/jasmine-marbles.spec.ts as below
4. ng test

**Expected Results**
Both tests pass

**Actual Results**
`jasmine-marbles should work using toPromise FAILED`
`        Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)`

**Notes**
I tried various combinations of `async( () => {...} )`, `async () => { ... }` and awaiting the promise, returning the promise, etc. but it doesn't seem to make any difference.

Despite the warning the test appears to work correctly, whether the promise is fulfilled or rejected. But given the complexity of asynchronous testing, the warning is rather concerning.

**src/jasmine-marbles.spec.ts**
```
import { cold } from 'jasmine-marbles';

describe('jasmine-marbles', () => {
  it('should work using an Observable', () => {
    const observable = cold('a|', { a: true });
    
    observable.subscribe(
      (value) => expect(value).toBe(true),
      fail
    );
  });

  it('should work using toPromise', () => {
    const promise = cold('a|', { a: true }).toPromise();
    
    return promise.then(
      (value) => expect(value).toBe(true),
      fail
    );
  });
});

```

**Comment by brandonroberts** [comment]
I would suggest using the `done` function in the test to make sure it waits until the observable emits a value.
