### ISSUE TITLE
toBeObservable not working with observable on top of promise

### ISSUE THREAD

**Issue by jbardon** [synapse-wireless-labs/jasmine-marbles#54]
With RxJS from version 6, a promise can be transformed into an Observable using the `from` operator. It seems, when an observable comes from a promise the `toBeObservable` matcher isn't working properly.

I think it's not due to `from` operator because when subscribing to both `actual$` and `expected$` observables the output are the same.

**How to reproduce**

```js
it('expected observable should match promise observable', () => {
    const resultPromise = Promise.resolve(false);
    const actual$ = from(resultPromise);

    const expected$ = cold('(a|)', { a: false });
    expect(actual$).toBeObservable(expected$);
})
```

**Actual result**

`toBeObservable` fails despite the two observables are equal.
```
Error: Expected $.length = 0 to equal 2.
        Expected $[0] = undefined to equal Object({ frame: 0, notification: Notification({ kind: 'N', value: false, error: undefined, hasValue: true }) }).
        Expected $[1] = undefined to equal Object({ frame: 0, notification: Notification({ kind: 'C', value: undefined, error: undefined, hasValue: false }) }).
```

**Expect result**

`toBeObservable` should succeed because the two observable are equal.

**Comment by PhilippMeissner** [comment]
Having the same issue. Our current workaround is to falsely implement the mock that returned a `Promise` within the stream (and was converted to an observable on the way).

**Comment by brandonroberts** [comment]
If you have a fix in mind, a PR will be gladly accepted

**Comment by brandonroberts** [comment]
Please re-verify with the latest `0.7.0` release
