### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bryanforbes** [synapse-wireless-labs/jasmine-marbles#61]
It's been over a year since the last release. Could we get a new release at least with the better error reporting?

**Comment by brandonroberts** [comment]
Yep, I'll cut a release tomorrow

**Comment by brandonroberts** [comment]
Version `0.7.0` has been published to npm

**Comment by brandonroberts** [comment]
Use `0.8.1` instead

**Comment by bryanforbes** [comment]
Thank you!
