### ISSUE TITLE
marble tests failing with rxjs 7

### ISSUE THREAD

**Issue by ashwanikrsingh** [synapse-wireless-labs/jasmine-marbles#73]
Version:

1.      jasmine-marbles: 0.8.1
2.     rxjs: 7.1.0

Recently i upgarded my project to rxjs 7, but after upgrading all marble tests are failing.
Marble tests are written to test the ngrx effects.
I am pasting here snapshot of one of the failed tests.
![image](https://user-images.githubusercontent.com/48906602/121535700-ae6c2380-ca02-11eb-9607-441e036abc54.png)

So my question, is it because the versions are not compatible or it should not have happen at all ?

**Comment by brandonroberts** [comment]
This has already been fixed and I just published `0.9.0-beta.0`. Try it out and see if it solves the failing tests

**Comment by ashwanikrsingh** [comment]
Thanks Brandon, this upgrade worked like a charm
